swagger: "2.0"
info:
  version: "1.0.0"
  title: "Farztev admin"
  contact:
    email: "mathieu@ronvel.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
schemes:
- "http"
paths:
  /articles:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SmallArticle"
        400:
          description: "Invalid status value"
  /articles/{articleId}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "articleId"
        in: "path"
        description: "ID of the article to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Article"
        404:
          description: "Article not found"
definitions:
  SmallArticle:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      country:
        type: "country"
        example: "fr"
      name:
        type: "string"
        example: "Visit in Dublin"
      photo:
        type: "string"
        example: "dublin.jpg"
  Article:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      country:
        type: "country"
        example: "fr"
      name:
        type: "string"
        example: "Visit in Dublin"
      photo:
        type: "string"
        example: "dublin.jpg"
      description:
        type: "string"
        example: "Dublin is the capital of Irland..."
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"